### ISSUE TITLE
Setup a CI process

### ISSUE THREAD

**Issue by niltonvasques** [Catbag/redux-android-sample#15]

**Comment by raulccabreu** [comment]
I posted a pull request that is one step to closes this

**Comment by niltonvasques** [comment]
@raulccabreu Take a look at this: http://blog.mockito.org/2014_08_01_archive.html
https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md

Those guys uses a continuos deployment with auto merge changes and auto versioning releases. Since, the PR pass in all required status. (Tests coverage, Tests and etc)

Example of an auto merged PR: https://github.com/mockito/mockito/pull/693
