### ISSUE TITLE
Clean up Lint Warnings

### ISSUE THREAD

**Issue by raulccabreu** [Catbag/redux-android-sample#19]
See the report and go cleaning...
[Lint Warnings Report](https://github.com/Catbag/flux-android-sample/files/530672/lint.pdf)

**Comment by fpbitencourt** [comment]
Uma vez que limpar completamente os _lint warnings_ é uma missão improvável de ser finalizada, essa _issue_ não deveria ser mais uma tarefa rotineira do nosso processo de desenvolvimento? Analisar e corrigir os warnings gerado pelo seu novo código e até os antigos. Os _warnings_ relevantes mas que por algum motivo não pôde ser resolvido no _PR_ entraria como _issue_.

**Comment by raulccabreu** [comment]
One option is not make pushes that grows the number of warnings...but first we have to try to clean all one time, then try to keep the numbers the same as possible.

**Comment by raulccabreu** [comment]
This issue don't need to be made on this sample project (this issue was be copied to production related project)
