### ISSUE TITLE
Activate proguard on project because methods limit

### ISSUE THREAD

**Issue by raulccabreu** [Catbag/redux-android-sample#56]
Project + dependencies are passing the methods limit of dex

> I think your dex file is reached to its maximum method count. Try to use `multiDexEnabled true`
> in your deafault config or try to minmize your playservices from your dependencies. Use only required > packages. Try changing your version or exclude unwanted packages

**Comment by niltonvasques** [comment]
Already? We need discover which is the dependency that are pushing this limit.

**Comment by raulccabreu** [comment]
Avoid the 64K limit

Before configuring your app to enable use of 64K or more method references, you should take steps to reduce the total number of references called by your app code, including methods defined by your app code or included libraries. The following strategies can help you avoid hitting the DEX reference limit:

    Review your app's direct and transitive dependencies - Ensure any large library dependency you include in your app is used in a manner that outweighs the amount of code being added to the app. A common anti-pattern is to include a very large library because a few utility methods were useful. Reducing your app code dependencies can often help you avoid the DEX reference limit.
    Remove unused code with ProGuard - Enable code shrinking to run ProGuard for your release builds. Enabling shrinking ensures you are not shipping unused code with your APKs.

Using these techniques might help you avoid the need to enable multidex in your app while also decreasing the overall size of your APK.

**Comment by raulccabreu** [comment]
This issue don't need to be implemented on this sample project, only on a production ready one (this issue was be copied to production related project)
