### ISSUE TITLE
Move this project from Catbag Drone to Drone.io

### ISSUE THREAD

**Issue by raulccabreu** [Catbag/redux-android-sample#65]
Unlimited free builds for public repositories to https://drone.io/

**Comment by niltonvasques** [comment]
I make some tests on drone.io and looks like that isn't possible, because they don't allow customizing builds. And they don't have android builds support. I'm thinking in moving to travis. What do you think?

**Comment by raulccabreu** [comment]
For me, we don't need this so great level of security...keep this project on catbag drone. Close this issue if you agree.

**Comment by niltonvasques** [comment]
:+1:
